pkcs11.h: fix build with latest libnss
Build is broken with libnss in version 3.66 and
https://github.com/nss-dev/nss/commit/595deb8fbce65e931935fb7e22aea785cb6016ad
because CK_NSS_GetFIPSStatus is undefined as _pkcs11h-crypto-nss.c is
defining _PKCS11T_H_:

In file included from /home/buildroot/autobuild/instance-1/output-1/host/bin/../arc-buildroot-linux-gnu/sysroot/usr/include/nss/keythi.h:10,
                 from /home/buildroot/autobuild/instance-1/output-1/host/bin/../arc-buildroot-linux-gnu/sysroot/usr/include/nss/cert.h:21,
                 from _pkcs11h-crypto-nss.c:58:
/home/buildroot/autobuild/instance-1/output-1/host/bin/../arc-buildroot-linux-gnu/sysroot/usr/include/nss/secmodt.h:79:5: error: unknown type name 'CK_NSS_GetFIPSStatus'
   79 |     CK_NSS_GetFIPSStatus fipsIndicator;
      |     ^~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/1e8113d638fcb73538329511eeac9f5e7cb04d6a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>